/* DayPay — Know what your work is worth.
   Copyright © 2026 Akaninyene. All rights reserved.
   Unauthorized copying, modification, or distribution is prohibited. */

/*
  Materialise .env from config/supabase-public.env.

  WHY THIS EXISTS

  Vite only exposes variables that are present at build time, from a file in
  the project root called .env (or .env.local, .env.production, …). It does
  NOT read config/supabase-public.env — that name means nothing to Vite.

  The public config is committed, but .env is gitignored and gets stripped
  when the sandbox is rebuilt. So a build run after a rebuild silently
  produced a bundle with NO Supabase URL and NO key: the app booted, looked
  fine, and simply said "Cloud sync not configured." Nothing errored. The
  whole cloud half of the product was quietly absent — no sign-in, no roster,
  no Join tab.

  That is the exact failure this module prevents: it fills in .env before
  Vite reads the environment, so the build always sees the config.

  RULES
    - Never overwrites a value that .env already sets. If you have a real
      .env pointing at a different project, that wins. This only fills gaps.
    - Only ever copies VITE_ / NEXT_PUBLIC_ keys. Those are public by
      definition — they ship inside the browser bundle on every load.
    - Refuses to copy anything matching a secret shape, so a stray
      sb_secret_ / service_role / sbp_ value can never be promoted into a
      build.
*/

import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'

const ALLOWED_PREFIXES = ['VITE_', 'NEXT_PUBLIC_']
const PUBLIC_URL_SHAPE = /^https:\/\/[a-z0-9]+\.supabase\.co$/i

/** Anything that must never reach a browser bundle. Returns a reason, or null. */
export function looksSecret(key, value) {
  if (/^sb_secret_/.test(value)) return 'secret key (sb_secret_…)'
  if (/^sbp_/.test(value)) return 'personal access token (sbp_…)'
  if (/service_role/.test(value)) return 'service_role reference'
  if (key.includes('SERVICE_ROLE') || key.includes('PASSWORD')) {
    return 'a name that implies service/password'
  }
  // A legacy JWT: read the role claim out of the middle segment.
  const parts = value.split('.')
  if (parts.length === 3 && value.startsWith('eyJ')) {
    try {
      const payload = JSON.parse(
        Buffer.from(parts[1].replace(/-/g, '+').replace(/_/g, '/'), 'base64').toString('utf8')
      )
      if (payload.role === 'service_role') return 'service_role JWT'
    } catch {
      /* not decodable — treated as opaque */
    }
  }
  return null
}

function parse(text) {
  const out = []
  for (const raw of text.split(/\r?\n/)) {
    const line = raw.trim()
    if (!line || line.startsWith('#')) continue
    const eq = line.indexOf('=')
    if (eq < 1) continue
    out.push([line.slice(0, eq).trim(), line.slice(eq + 1).trim().replace(/^["']|["']$/g, '')])
  }
  return out
}

/**
 * Ensure <root>/.env carries the public Supabase config.
 * Throws on a missing or malformed public file so a bad build cannot proceed.
 * Returns { url, key } so the caller can assert the bundle really got them.
 */
export function prepareEnv(root = process.cwd(), { quiet = false } = {}) {
  const publicFile = path.join(root, 'config', 'supabase-public.env')
  const target = path.join(root, '.env')

  if (!fs.existsSync(publicFile)) {
    throw new Error(
      `prepare-env: ${path.relative(root, publicFile)} is missing. ` +
        'It is committed and holds the public Supabase URL and publishable key.'
    )
  }

  const existing = fs.existsSync(target) ? parse(fs.readFileSync(target, 'utf8')) : []
  const have = new Set(existing.map(([k]) => k))

  const additions = []
  for (const [key, value] of parse(fs.readFileSync(publicFile, 'utf8'))) {
    if (!ALLOWED_PREFIXES.some((p) => key.startsWith(p))) continue
    if (have.has(key)) continue
    const secret = looksSecret(key, value)
    if (secret) {
      console.warn(`prepare-env: REFUSING to copy ${key} — looks like ${secret}.`)
      continue
    }
    additions.push([key, value])
  }

  if (additions.length) {
    const header = existing.length
      ? ''
      : '# Generated by scripts/prepare-env.mjs from config/supabase-public.env.\n' +
        '# Public by design — both values ship inside the browser bundle.\n' +
        '# A real secret must never be added here; see the notes in that file.\n'
    const body = additions.map(([k, v]) => `${k}=${v}`).join('\n')
    fs.writeFileSync(target, header + body + '\n', { flag: existing.length ? 'a' : 'w' })
    if (!quiet) console.log(`prepare-env: filled .env with ${additions.map(([k]) => k).join(', ')}`)
  } else if (!quiet) {
    console.log(`prepare-env: .env already complete (${existing.length} entries)`)
  }

  const map = new Map(parse(fs.readFileSync(target, 'utf8')))
  const url = map.get('VITE_SUPABASE_URL') || map.get('NEXT_PUBLIC_SUPABASE_URL') || ''
  const key =
    map.get('VITE_SUPABASE_ANON_KEY') ||
    map.get('VITE_SUPABASE_PUBLISHABLE_KEY') ||
    map.get('NEXT_PUBLIC_SUPABASE_ANON_KEY') ||
    ''

  if (!PUBLIC_URL_SHAPE.test(url)) {
    throw new Error(`prepare-env: VITE_SUPABASE_URL is not a Supabase project URL: ${JSON.stringify(url)}`)
  }
  const secret = looksSecret('VITE_SUPABASE_ANON_KEY', key)
  if (secret) throw new Error(`prepare-env: the browser key is ${secret}. Use the publishable/anon key.`)
  if (key.length < 20) {
    throw new Error('prepare-env: the anon/publishable key looks empty or truncated.')
  }

  return { url, key, wrote: additions.length > 0 }
}

/* Direct invocation: node scripts/prepare-env.mjs */
const invokedDirectly =
  process.argv[1] && import.meta.url === pathToFileURL(path.resolve(process.argv[1])).href

if (invokedDirectly) {
  const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
  try {
    const { url, key } = prepareEnv(root)
    console.log(`prepare-env: ok — ${url.replace(/^https:\/\//, '').split('.')[0]} / ${key.slice(0, 15)}…`)
  } catch (e) {
    console.error(e.message)
    process.exit(1)
  }
}
